name: Release
on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
      - '.changeset/**'
      - '.github/workflows/release.yml'

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  version:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Create versions PR & prepare publish
        id: changesets
        uses: changesets/action@master
        # if: github.ref == 'refs/heads/master'
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          # Messages
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
        env:
          # npm publish token required for publishing. Set this in secrets
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # automatically available in actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
